"""Report generation (branded PDF/HTML/JSON) and honest tool-health reporting."""
from __future__ import annotations

import json
from pathlib import Path

from app.modules.cases import service as cases
from app.modules.evidence import service as evidence
from app.modules.findings import service as findings
from app.modules.hashing import service as hashing
from app.modules.reports import service as reports


def test_report_generation_all_formats(samples):
    case = cases.create("Unit report case", "generated by pytest")
    ev = evidence.import_file(case["id"], samples["image_png"])
    hashing.hash_file(samples["image_png"], case_id=case["id"], evidence_id=ev["id"])
    findings.create(case["id"], title="Unit finding", severity="Informational",
                    category="Steganography", description="added for the report body")

    outputs = {row["format"]: row for row in reports.generate(case["id"])}
    assert set(outputs) == {"pdf", "html", "json"}

    pdf = Path(outputs["pdf"]["path"])
    assert pdf.read_bytes()[:5] == b"%PDF-"
    html = Path(outputs["html"]["path"]).read_text(encoding="utf-8")
    assert "<html" in html.lower() and "StegoNexus" in html
    data = json.loads(Path(outputs["json"]["path"]).read_text(encoding="utf-8"))
    assert data["case"]["id"] == case["id"]


def test_tool_health_reports_required_and_honest():
    from app.services.tool_health import health

    summary = health.summary()
    assert summary["total"] > 0
    # missing_required is a list of names; it must be empty on a working install.
    assert not summary["missing_required"]

    rows = {row["name"]: row for row in summary["rows"]}
    # Core Python-backed capabilities must be present in any working install.
    for lib in ("PySide6", "PIL", "numpy", "cryptography", "scapy"):
        assert rows[lib]["available"] is True

    # zsteg must never be presented as implemented when it is not installed.
    if not rows["zsteg"]["available"]:
        assert rows["zsteg"]["classification"] in ("UNAVAILABLE", "REFERENCE", "OPTIONAL")
